config/routes.rb
Inaika::Application.routes.draw do

  get "landing_page/thankyou"
  get "landing_page/faq"
  get "landing_page/conditions"
  get "landing_page/contact"
  get "landing_page/main"
  get "landing_page/new"

  match 'landing_page/new' => 'landing_page#new', :as => 'landing_page', :via => :get
  match 'landing_page/new' => 'landing_page#create', :as => 'landing_page', :via => :post  
  match 'thankyou' => 'landing_page#thankyou'
  match 'faq' => 'landing_page#faq'
  match 'conditions' => 'landing_page#conditions'
  match 'contact' => 'landing_page#contact'
  match 'revolution' => 'landing_page#new'
  match 'landing_page' => 'landing_page#main'
  
  

  root :to => 'demo#welcome'

  get 'demo/student_account'
  get 'demo/student_calendar'
  get 'demo/payment'
  get 'demo/results'
  get "demo/welcome"
  get 'demo/student_profile'
  get 'demo/search'
  get 'demo/teacher_profile_john'
  get 'demo/teacher_calendar'
  get 'demo/oops'
  get 'demo/end'  
  get 'demo/shared_class_info'
  get 'demo/confirmation'
  get 'demo/new_review'

  match 'demo' => 'demo#welcome'
  match 'demo/feedback' => 'demo#new'
  match 'demo/new' => 'demo#new', :as => 'demo', :via => :get
  match 'demo/new' => 'demo#create', :as => 'demo', :via => :post  
  match 'demo/feedback_thankyou' => 'demo#feedback_thankyou'
  match '/student_signup_demo', to: 'demo#student_signup'
  match '/teacher_signup_demo', to: 'demo#teacher_signup'
  match '/student_signup_demo', to: 'students#new_demo'

  

end

app/models/message.rb
class Message
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :name, :email, :location, :video_link

	validates :name, :email, :video_link, :presence => true
	validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
	
	def initialize(attributes = {})
    	attributes.each do |name, value|
      		send("#{name}=", value)
    	end
  	end

  	def persisted?
  		false
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
	def welcome
	end

	def signup
	end

	def search
	end

	def student_signup
		
	end

	def teacher_signup
	end

	def student_profile
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(params[:message])
    
	    if @message.valid?
	      Mailer.new_feedback_message(@message).deliver
	      redirect_to("/demo/feedback_thankyou", :notice => "Message was successfully sent.")
	    else
	      flash.now.alert = "Please fill all fields."
	      render :new    
	    end
	end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

  def new
    @message = Message.new
    
  end

  def main
  end

  def thankyou
  	
  end

  def create
  	@message = Message.new(params[:message])
    
    if @message.valid?
      Mailer.new_message(@message).deliver
      redirect_to("/landing_page/thankyou", :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new    
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (page_title)
		base_title = "Inaika - Find a teacher you'll love!"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def logged_in (page_name)
		if (page_name.eql?'welcome') or (page_name.eql? 'student_signup')
			return false	
		else
			return true
		end	
	end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
	def is_main_page(page_name)
		return page_name.eql? "main"
	end
end

app/views/demo/confirmation.html.erb
<div class="box box-student">
	<div class="box-inner">
		<h2>Congratulations, you've booked your class!</h2>
		<h3>Golf Class with John Smith</h3>
		<h3>
			Date
		</h3>
		<p>July 4, 2012</p>
		<h3>Time</h3>
		<p>9am - 12pm</p>
		<h3>Location</h3>
		<p>Farmington Driving Range<br />
			2321 Towncrest Road<br />
			San Jose, CA 95035</br>
		</p>
		<h3>Total Cost</h3>
		<p>$120<br />
			<em>(Note: This is a shared class. If more students join, the price will go down. You will be charged the lowest price.)</em>
		</p>
		<br />
		<p>
				This class has been saved to your calendar.
			You can set reminder options by visiting the class scheduled on your calendar.
		</p>	

		<%= link_to "My Calendar", "student_calendar", class: "btn btn-large btn-primary" %>
	</div>
</div>

app/views/demo/new.html.erb
<div class="row">
	<div class="box box-student span6">
		<div class="box-inner">
				<h2>Share your thoughts with us</h2>

				<div class="row">
				  <div class="span5">
				      <%= form_for @message, :url => demo_path  do |form| %> 
				        <%= form.error_messages :header_message => "Submission Failed", :message => nil %>       
				            <%= form.text_field :name, placeholder:"Your name"%><br />              
				            <%= form.text_field :email, placeholder:"Your email" %><br />                
				            <%= form.text_area :video_link , placeholder:"Your comments" %><br />                            
				          <%= form.submit "Submit Feedback", class:"btn btn-large"%>
				      <% end %>
				  </div>
				</div>
		</div>
	</div>
</div>

app/views/demo/new_review.html.erb
<div class="box box-student">
  <div class="box-inner">

      <h2>New Review for Laura Rodriguez</h2>
                      
            <%= link_to (image_tag "profile/laura_profile.jpg", class: "img profile-img profile-img-teacher"), "teacher_profile_john" %>
            <h3>Spanish Teacher</h3>            

            <br />
            <h3>How was your experience with Laura?</h3>
            <div class="controls">
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="positive" checked>
                <%= image_tag "icon_positive.png" %>  <strong>Positive</strong> - I would recommend Laura to my friends.
              </label>
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios2" value="neutral">
                <%= image_tag "icon_neutral.png" %> <strong>Neutral</strong>
              </label>
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios2" value="negative">
                <%= image_tag "icon_negative.png" %>  <strong>Negative</strong> - I would not recommend Laura to any friends.
              </label>
            </div>

            <br />
            <h3>What are some words you would use to describe Laura as a teacher?</h3>
            <input type="text" placeholder:"For example: 'organised', 'friendly', 'professional', 'punctual' etc." />

           	<h3>Write a little more about your learning experience with Laura here:</h3>
           	<textarea rows="10"></textarea>
           	<%= link_to "Save Review", "student_profile", class: "btn btn-large btn-primary" %>
  </div>

</div>

app/views/demo/payment.html.erb

<div class="box box-student">
  <div class="box-inner">
        <h2>Payment Info</h2>
        <div>
              <h3>Class Details</h3>
              <p>Date: July 4, 2012</p>
              <p>Time: 9am - 11pm </p>
              <p>Location: Farmington Driving Range. 2321 Towncrest Road, San Jose, CA 95035
                <%= link_to "(Show on map)", "#" %></p>
              </p>
         </div>
            <div class="control-group">
            <h3>Select Payment Option:</h3>
            <div class="controls">
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="card1" checked>
                VISA credit card ending in 9876
              </label>
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios2" value="paypal">
                Paypal
              </label>
              <label class="radio">
                <input type="radio" name="optionsRadios" id="optionsRadios2" value="newcard">
                Add new card
              </label>
            </div>
          </div>
          <h3>Cancellation Policy</h3>
          <p><strong>Yes! You can cancel this class and receive a full refund</strong>, any time up to 48 hours before the class date. You can also reschedule the class for a different date. This cancellation policy is decided by your teacher, not Inaika.</p>
          <%= link_to "Book this class!", "confirmation", class: "btn btn-large btn-primary" %>        
  </div>
</div>

app/views/demo/results.html.erb
<div>
  <h2>Here are some awesome golf teachers near Milpitas, CA:</h2>
  <div class="row">
      <div class="span3">
          <div class="control-group">
            <label class="control-label" for="select01">Sort by:</label>
            <div class="controls">
              <select id="select01">
                <option>Reviews</option>                
                <option>Price</option>
              </select>
            </div>
          </div>
      </div>
</div>

<div class="box box-teacher">
  <div class="row">
        <div class="span2 box-profile-img">
          <%= link_to (image_tag "profile/john_profile.jpg", class:"img profile-img"), "teacher_profile_john" %>
          <h3>John Smith</h3>
          <p>San Jose, CA<br /><strong>From $50/hour</strong></p>       
        </div>
        <div class="span7">
          <div class="row">
            <div class="span4 box-profile-details">
              <h3>Learn from John</h3>
              <p>I'm John, a professional golf instructor with over 10 years of experience teaching beginners in the Bay Area.</p>        
              <button class="btn">punctual</button>
              <button class="btn">enthusiastic</button>
              <button class="btn">helpful</button>              
            </div>
            <div class="span3 box-profile-details">
              <h3>Watch John in Action</h3>
              <iframe width="210" height="150" src="http://www.youtube.com/embed/K8qZV79NN6k" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="row">
            <div class="span7 box-profile-details" id="profile-lower">
              <p><%= image_tag "icon_level.png" %> Levels: Beginner, Intermediate, Advanced</p>
              <p><%= image_tag "icon_bgcheck.png" %> Background Check   <%= image_tag "icon_credit.png" %> Accepts Credit Cards</p>
            </div>
          </div>
        </div>
        <div class="span3 box-recommendations">
          <h3>Read John's 12 Reviews</h3>
            <p><%= image_tag "icon_positive.png" %> 10 positive<br /><%= image_tag "icon_neutral.png" %> 2 neutral<br /><%= image_tag "icon_negative.png" %> 0 negative</p>
            <p>3 of your friends recommend John</p>
              <%= image_tag "profile/wayne_profile_mini.jpg", class:"img profile-img" %>
              <%= image_tag "profile/mag_profile_mini.jpg", class:"img profile-img" %>              
              <%= image_tag "profile/michelle_profile_mini.jpg", class:"img profile-img" %> 

              <p>Hover over your friend to see what they say!</p>                                
        </div>  
  </div>
</div>

<br />

<div class="box box-teacher">
   <div class="row">
        <div class="span2 box-profile-img">
          <%= link_to (image_tag "profile/sarah_profile.jpg", class:"img profile-img"), "teacher_profile_john" %>
          <h3>Sarah Brown</h3>
          <p>Sunnyvale, CA<br /><strong>From $45/hour</strong></p>       
        </div>
        <div class="span7">
          <div class="row"> 
            <div class="span4 box-profile-details">
              <h3>Learn from Sarah</h3>
              <p>I'm Sarah, I teach beginners.</p>        
              <button class="btn">passionate</button>              
              <button class="btn">helpful</button>
              <button class="btn">experienced</button>
            </div>
            <div class="span3 box-profile-details">
              <h3>Watch Sarah in Action</h3>              
              <%= image_tag "no_video.jpg" %>
            </div>
          </div>
          <div class="row">
            <div class="span7 box-profile-details" id="profile-lower">
              <p><%= image_tag "icon_level.png" %> Levels: Beginner</p>
              <p><%= image_tag "icon_bgcheck.png" %> Background Check   <%= image_tag "icon_credit.png" %> Accepts Credit Cards</p>                
            </div>
          </div>
        </div>
        <div class="span3 box-recommendations">
          <h3>Read Sarah's 5 Reviews</h3>
            <p><%= image_tag "icon_positive.png" %> 4 positive<br /> <%= image_tag "icon_neutral.png" %> 1 neutral<br /> <%= image_tag "icon_negative.png" %> 0 negative</p>
            <p>2 of your friends recommend Sarah</p>
              <%= image_tag "profile/nick_profile_mini.jpg", class:"img profile-img" %>
              <%= image_tag "profile/mag_profile_mini.jpg", class:"img profile-img" %>                      
              <p>Hover over your friend to see what they say!</p>
            
        </div>  
  </div>
</div>
<br />

<div class="box box-teacher">
   <div class="row">
        <div class="span2 box-profile-img">
          <%= link_to (image_tag "profile/jerry_profile.jpg", class:"img profile-img"), "teacher_profile_john" %>
          <h3>Jerry Larson</h3>
          <p>Saratoga, CA<br /><strong>From $60/hour</strong></p>       
        </div>
        <div class="span7">
          <div class="row"> 
            <div class="span4 box-profile-details">
              <h3>Learn from Jerry</h3>
              <p>I specialize in teaching intermediate and advanced level students in the Bay Area.</p>
              <button class="btn">friendly</button>              
              <button class="btn">enthusiastic</button>
              <button class="btn">experienced</button>
            </div>
            <div class="span3 box-profile-details">
              <h3>Watch Jerry in Actions</h3>
              <%= image_tag "no_video.jpg" %>
            </div>
          </div>
          <div class="row">
            <div class="span7 box-profile-details" id="profile-lower">
              <p><%= image_tag "icon_level.png" %> Levels: Intermediate, Advanced</p>                
              <p><%= image_tag "icon_bgcheck.png" %> Background Check   <%= image_tag "icon_credit.png" %> Accepts Credit Cards</p>                
            </div>
          </div>
        </div>
        <div class="span3 box-recommendations">
          <h3>Read Jerry's 2 Reviews</h3>
            <p><%= image_tag "icon_positive.png" %> 2 positive<br /> <%= image_tag "icon_neutral.png" %> 0 neutral <br /> <%= image_tag "icon_negative.png" %> 0 negative</p>
            <p>0 of your friends recommend Jerry.</p>                            
        </div>  
  </div>
</div>

app/views/demo/shared_class_info.html.erb
<h1>This is how a shared class works</h1>

<p>Explanation.</p>

app/views/demo/student_account.html.erb
<div class="box box-student">
	<div class="box-inner">
		<h2>Your Account Settings</h2>
		<h3>Address</h3>
		<p>1234 Main Street, Milpitas, CA, USA.</p>
		<%= link_to "Edit", "#" %>

		<br />
		<br />
		<h3>Payment Options</h3>

		<p>You have the following credit cards saved.</p>
		<p>VISA card ending in 9504</p>
		<p>Mastercard card ending in 6011</p>

		<%= link_to "Add a new card", "#" %>
	</div>
</div>	

app/views/demo/student_calendar.html.erb

    <div class="box box-teacher">

      <div class="row">
        <div class="span2 box-profile-img">
          <%= image_tag "profile/wayne_profile.jpg", class:"img profile-img" %>         
        </div>
        <div class="span10">
          <h2>Your Calendar</h2>                  
          <button class="btn btn-success" style="width:150px">Private Class</button><br />
          <button class="btn btn-warning" style="width:150px">Shared Class</button><br />
          <button class="btn btn-danger" style="width:150px">Booked</button><br />
        </div>
      </div>

    <br />
    <hr />

    <div id="johns_calendar">
      <div class="row" align="center">

      </div>
      
      <div class="row">
        <%= render 'layouts/calendar_student' %>
      </div>
    </div>
  </div>

    <br />
    <div id="booking_info">
        <h3>You have selected a class with John Smith :</h3>
        <p>Type: <button class="btn btn-warning">Shared Class</button>
          <%= link_to "(How does this work?)", "shared_class_info" %></p>
        <p>Current Class Size: <strong>3/10 people</strong></p>
        <p>Minimum Required for class: <strong> 2 people</strong></p>  
        <p>Current Cost: <strong>$120 per person</strong></p>
        <p>- If 2 more people sign up, the cost will come down to: <strong>$90 per person</strong></p>
        <p>- If 7 more people sign up, the cost will come down to: <strong>$50 per person</strong></p>
        <p>Invite your friends! Share this link: <em>http://www.inaika.com/demo/johns_golf_class</em></p>

        <br />
        
        <h3>Class Details</h3>
        <p>Date: July 4, 2012</p>
        <p>Time: 9am - 11pm </p>
        <p>Location: Farmington Driving Range. 2321 Towncrest Road, San Jose, CA 95035
          <%= link_to "(Show on map)", "#" %></p>
        </p>

        <br />

        <h3>Reminder Options</h3>

        <p>Reminder Time: July 3, 2012.</p>
        <p>Reminder Method: Text Message</p>
        <%= link_to "Edit Options", "#" %>
        <br />
        <br />
        <br />
        
    </div>
  
    <div id="booking_buttton">
      <%= link_to "Cancel Class", "#", class: "btn btn-large btn-primary", style: "width: 200px" %>        
    </div>
  

app/views/demo/student_profile.html.erb
<% provide(:page_name, 'student_profile') %>
	
	<!-- my profile and search -->	
		<div class="row">			
				<div class="span6 box box-me">						
						<div class="row">							
							<div class="span2 box-profile-img">							
									<%= image_tag "profile/wayne_profile.jpg", class:"profile-img" %>															    					
							</div>
							<div class="span4 box-profile-details">								
										<h2>Wayne Lin</h2>
										<p>Milpitas, CA</p>								
										<h3>Interests</h3>
										<p>Tennis, Golf, Knitting, Cooking, Basket Weaving</p>										
							</div>						
						</div>	
						<div class="row">
							<div class="span6 box-profile-details">
								<p>Other profile information here.</p>
								<p>Other profile information here.</p>
								<p>Other profile information here.</p>								
							</div>
						</div>				
				</div>

				<div class="span6 box box-search">						
						<h2>Find a teacher!</h2>
						<h3>What do you want to learn?</h3>
						
					  	<input type="text" class="input span6 search-query" placeholder="Spanish, golf, salsa, web design, singing, writing, cooking..." ><br />
					  	
					  	<h3>Where?</h3>
					  	
					  	<input type="text" class="input span6 search-query" value="Milpitas, CA">
					  	<div>
					  		<%= link_to "Search", "results", class:"btn btn-large btn-primary" %>				  				
					  	</div>					
				</div>

		</div>

	<br />

	<!-- suggested teachers -->
	<div class="suggested_teachers" >
		<h2>Thinking about learning something new?</h2>
		<p>Here are some of the teachers your friends thought were awesome:</p>		
			<div class="box box-teacher">
				<div class="row">				
					<div class="span2 box-profile-img">
						<%= link_to (image_tag "profile/carlos_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Carlos</h3>
						<p>Guitar</p>
					</div>
					<div class="span2 box-profile-img">
						<%= link_to (image_tag "profile/maryann_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Mary-Ann</h3>
						<p>Cooking</p>
					</div>
					<div class="span2 box-profile-img">
						<%= link_to (image_tag "profile/adam_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Adam</h3>
						<p>Karate</p>
					</div>
					<div class="span2 box-profile-img">
						<%= link_to (image_tag "profile/karen_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Karen</h3>
						<p>German</p>
					</div>				
					<div class="span2 box-profile-img">					
						<%= link_to (image_tag "profile/paul_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Paul</h3>
						<p>Biology</p>
					</div>
					<div class="span2 box-profile-img">					
						<%= link_to (image_tag "profile/monica_profile.jpg", class: "img profile-img"), "teacher_profile_john" %>
						<h3>Monica</h3>
						<p>Swimming</p>
					</div>
				</div>		
			</div>
	</div>

	<br />
	<!-- your teachers -->
	<div id="your_teachers">
			<h2>Your Teachers</h2>
			<p>These are the rockstars who inspire your passion in learning.
				<div class="box box-teacher">
					<div class="row">		
						<div class="span2 box-profile-img">
							<%= link_to (image_tag "profile/john_profile.jpg", class: "img profile-img profile-img-teacher"), "teacher_profile_john" %>
							<h3>John Smith</h3>
							<p>Golf</p>
						</div>
						<div class="span7">
							<h3><%= image_tag "icon_positive.png" %> Positive</h3>
							<p>John is an excellent teacher, particularly well suited for beginners. He is patient, encouraging and most importantly very knowledgeable about the difficulties that new students face when starting to learn golf. He's excellent at explaining and showing to students the different techniques.<p>
							<p>The driving range he teaches at is a little further away from the city, but very well maintained and has great service. I strongly recommend John to any beginners trying to learn golf.
							</p>
							<button class="btn">punctual</button>
              				<button class="btn">patient</button>
              				<button class="btn">helpful</button><br />              				
							<p><%= link_to "Edit your review", "new_review" %></p>
						</div>
						<div class="span3">
							<h3>John's Other Reviews</h3>
					            <p><%= image_tag "icon_positive.png" %> 9 positive<br /><%= image_tag "icon_neutral.png" %> 2 neutral<br /><%= image_tag "icon_negative.png" %> 0 negative</p>
					            <p>2 of your friends recommend John</p>					              
					              <%= image_tag "profile/mag_profile_mini.jpg", class:"img profile-img" %>              
					              <%= image_tag "profile/michelle_profile_mini.jpg", class:"img profile-img" %> 					           
						</div>
					</div>
				</div>
				<br />
				<div class="box box-teacher">
					<div class="row">
						<div class="span2 box-profile-img">
							<%= link_to (image_tag "profile/laura_profile.jpg", class: "img profile-img profile-img-teacher"), "teacher_profile_john" %>
							<h3>Laura Rodriguez</h3	>
							<p>Spanish</p>
						</div>
						<div class="span7">
							<h3>Not Yet Reviewed</h3>
							<p>You haven't written a review for Laura yet. We strongly encourage you to write reviews for your teachers because:</p>
							<ul>
								<li>Reason A</li>
								<li>Reason B</li>
								<li>Reason C</li>
							</ul>
							<%= link_to "Write a review for Laura!", "new_review" %>
						</div>
						<div class="span3">
							<h3>Laura's Other Reviews</h3>
					            <p><%= image_tag "icon_positive.png" %> 4 positive<br /><%= image_tag "icon_neutral.png" %> 2 neutral<br /><%= image_tag "icon_negative.png" %> 0 negative</p>
					            <p>1 of your friends recommend Laura</p>					              
					              <%= image_tag "profile/steven_profile_mini.jpg", class:"img profile-img" %>              					              
						</div>
					</div>
				</div>
		</div>
	</div>

app/views/demo/student_signup.html.erb
<% provide(:page_name, 'student_signup') %>
<div class="page-header">
			<h1>So you're looking for a teacher?</h1>

		<!--
		<div class="row">	
			<div class="span6">
				<%= radio_button_tag(:user_type_student, "student") %> 
				I'm a <strong>student</strong>.<br />
				<em>I am looking for a teacher.</em>
			</div>
			<div class="span6">
				<%= radio_button_tag(:user_type_student, "teacher") %>
				I'm a <strong>teacher</strong>.<br />
				<em>I am looking for people to teach.</em>
			</div>
		</div>
	-->
	</div>

	<div id="facebook_signup">
		<div class="row">
			<div class="span12">
				<%= link_to image_tag("facebook_signup.png", alt: "Facebook Signup"), "demo/student_profile" %>
				<p>By clicking on the button above you agree to our <%= link_to "Terms of Service", "#" %> and <%= link_to "Privacy Policy", "#" %>.</p>
			</div>
		</div>
		<br />
		<div class="row" id="why_facebook">
			<div class="span12">
				<h3>Why do we use Facebook?</h3>				
				<ul>
					<li>Login securely with one click.</li>
					<li>Find awesome teachers through your friends.</li>					
					<li>Share & recommend teachers easily</li>
				</ul>
				<h3>Is my information safe?</h3>
				<p>Of course. Inaika will not sell any of your information to 3rd parties.</p>
			</div>			
		</div>
	</div>
	

app/views/demo/welcome.html.erb
<% provide(:page_name, 'welcome') %>
		<div class="box box-student hero-unit" style="height: 350px">			
				<center>
					<div style="width:850px">
					<br />
					<br />	
			
	  			<h1>Welcome to Inaika!</h1>
	  				<h5>the online platform that lets you find the teachers your friends have tried and loved</h5>
	  				<br />
	  				
	  				<h2 style="text-align: justified">This is a simple demo we've created to showcase some of Inaika's functionality. We're currently developing a working prototype and hope to have it ready for you soon. If you have any suggestions for us at this time, just click on the red "Feedback" button. Otherwise, feel free to begin exploring Inaika!</h2> 
	  				</div>
	  			</center>
  			
		</div>

		<div class="box" align="center">
			<div class="row">									
				<div class="span6">					
					<h2>Students find great teachers</h2><%= link_to "Student Sign Up", student_signup_demo_path, class: "btn btn-large btn-primary" %>				
				</div>		
				<div class="span6">
					<h2>Teachers find great students</h2><%= link_to "Teacher Sign Up", "#", class: "btn btn-large btn-primary" %>
				</div>
			</div>
		</div>

app/views/landing_page/contact.html.erb

<p>If you have any questions or concerns, please contact us at revolution@inaika.com</p>

<br />
<div><%= link_to "Return", "/" %></div>

app/views/landing_page/new.html.erb
<% provide(:page_name, 'main') %>
        
        <br />
<audio id="player" src="/here_comes_the_fire.ogg" ></audio>      
        <%= image_tag("landing_page/passion_revolution.png", id: "landing-slogan") %>
      
      
      <h4><br />
        Are you crazy about something?</h4> 
      
        <p>Do you love sports, play an instrument to the despair of your neighbours, sing in a shower or fanatically learn foreign languages? Or maybe your passion is so rare that it would never even cross our minds?</p>   
      
      <h4>Show it! Share it!</h4>
       <p>Send us a 2 minute video of you in action.<br />Make us feel what you feel and send a shiver down our spines!
      </p>

      <h4>Be part of our film!</h4>
      <p>
        The best submissions will be put together by our professional producers in a short film about inspiring passionate people around the world. The film will be featured on the Inaika website as well as promoted in the media. Additionally, the 3 winners of the Inaika - Passion Revolution competition will be invited to a professional shooting (at our studios in London or Warsaw) and will be featured as the main protagonists of our film!
      </p>
      <p>
        <%= link_to "Click here for more information", "faq" %>
      </p>
      <p>
        SUBMISSION DEADLINE:  5 August 2012, 11:59pm GMT
      </p>



        <br />

      <%= form_for @message, :url => landing_page_path do |form| %> 
        <%= form.error_messages :header_message => "Submission Failed", :message => nil %>       
            <%= form.text_field :name, placeholder:"Your name"%><br />              
            <%= form.text_field :email, placeholder:"Your email" %><br />      
            <%= form.text_field :location, placeholder:"Your location (eg. London, UK)" %><br />  
            <%= form.text_field :video_link , placeholder:"Your video link" %><br />                  
                
          <p>By clicking "Submit" you agree to our <%= link_to "Terms & Conditions", "conditions" %>.</p>
          <br />
          <%= form.submit "Submit My Video!", class:"btn btn-large"%>
      <% end %>

app/views/landing_page/thankyou.html.erb
      <h2>THANK YOU!</h2>
      <p>Your video submission for the INAIKA - PASSION REVOLUTION contest has been received!</p>
      <p>Winners will be notified after August 5th, 2012.</p>      

app/views/shared/_error_messages.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@student.errors.count, "error") %>.
    </div>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>